#!/bin/zsh

ssh () {
    setopt local_traps
    trap 'cxx' INT EXIT QUIT KILL
    dsa
    # Pick out user@host word from argv; if it's not found, default to $1.
    # Finally, strip off .* domain component, if any.
    cx "${${${(M@)argv:#*@*}:-$1}%%.[a-z]*}" 

    if [ -n "$SSH_ORIG_CLIENT" ]; then
        # see ~/.shared_rc.d/ssh
        export LC_TELEPHONE_ORIG="${LC_TELEPHONE}"
        export LC_TELEPHONE="${LC_TELEPHONE}^^export SSH_ORIG_CLIENT=${SSH_ORIG_CLIENT}"
        sshargs="-o SendEnv=LC_TELEPHONE"
        #sshargs="-o SendEnv=SSH_ORIG_CLIENT"
    fi

    command ssh $sshargs "$@"

    if [ "$+LC_TELEPHONE_ORIG" = 1 ]; then
        LC_TELEPHONE="${LC_TELEPHONE_ORIG}"
    fi
}
