#!/bin/sh

# Most Linux distributions seem to have AcceptEnv LC_TELEPHONE in
# /etc/ssh/sshd_config, so we can "tunnel" the environment values we
# want to pass over ssh through this to avoid having to reconfigure
# sshd_config everywhere, via:
#
#   export LC_TELEPHONE="${LC_TELEPHONE}^^SSH_ORIG_CLIENT=1.2.3.4"
#   ssh -o SendEnv=LC_TELEPHONE...


case "$LC_TELEPHONE" in
    *^^*)
        eval "${LC_TELEPHONE#*^^}"
        LC_TELEPHONE="${LC_TELEPHONE%^^*}" # just in case anything cares
        ;;
esac

# SSH_CLIENT always refers to the host which connected directly to
# this one, which is not always the first in the chain of ssh hops.
# It's useful to know the first too.
if [ -z "$SSH_ORIG_CLIENT" ]; then
    # Not passed via tunnelling hack above ...
    if [ -n "$SSH_CLIENT" ]; then
        # This is (hopefully) the server side of the first hop.
        export SSH_ORIG_CLIENT="${SSH_CLIENT%% *}"
    else
        : # We're not using ssh at all.
    fi
else
    : # Server side of seconder or greater hop.
fi
