#!/bin/sh

# Most Linux distributions seem to have AcceptEnv LC_TELEPHONE in
# /etc/ssh/sshd_config, so we can "tunnel" the environment values we
# want to pass over ssh through this to avoid having to reconfigure
# sshd_config everywhere, via:
#
#   export LC_TELEPHONE="${LC_TELEPHONE}^^SSH_ORIG_CLIENT=1.2.3.4"
#   ssh -o SendEnv=LC_TELEPHONE...


case "$LC_TELEPHONE" in
    *^^*)
        eval "${LC_TELEPHONE#*^^}"
        LC_TELEPHONE="${LC_TELEPHONE%^^*}"
        ;;
esac

if [ -z "$SSH_ORIG_CLIENT" ]; then
    if [ -n "$SSH_CLIENT" ]; then
        export SSH_ORIG_CLIENT="${SSH_CLIENT% *}"
    fi
fi
