#!/bin/bash

confdir=$HOME/.ssh
confsubdir=$confdir/config.d
config=$confdir/config

[ -d $confsubdir ] || mkdir -p $confsubdir

# source "$ZDOTDIR/.zsh/functions/enable_nullglob"
# dirents=`echo $confsubdir/*`
# [ -z "$dirents" ] && exit 0
# echo "parts $dirents"

source "$ZDOTDIR/lib/libhooks.sh"

rebuild_config "$config" "${confsubdir#$HOME/}"

chmod go-rwx -R $config $confdir $confsubdir
