#!/bin/bash

confdir=$HOME/.ssh
confsubdir=$confdir/config.d
config=$confdir/config

[ -d $confsubdir ] || mkdir -p $confsubdir
chmod go-rwx $confdir $confsubdir

# Ugh!
case "$BASH_VERSION" in
  1*)
    allow_null_glob_expansion=1
    ;;
  2*|3*)
    shopt -s nullglob
    ;;
  *)
    echo "Unknown \$BASH_VERSION $BASH_VERSION !  Aborting." >&2;
    exit 1
    ;;
esac

# dirents=`echo $confsubdir/*`
# [ -z "$dirents" ] && exit 0
# echo "parts $dirents"

. $ZDOTDIR/lib/libhooks.sh

rebuild_config "$config" "${confsubdir#$HOME/}"
